---
title: "Project 1"
author: Keshav Ramesh & Calista Harris
format: pdf
editor: visual
editor_options: 
  chunk_output_type: console
---

Load require packages
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```

# Data Processing

## Question 1: Reading in Data 

```{r}
edu01a <- read_csv("EDU01a.csv", show_col_types = FALSE) |>
  select(
    area_name = Area_name, #rename Area_name
    STCOU,
    ends_with("D") #select all columns ending in "D"
  )

#display the first 5 rows
edu01a |> 
  slice(1:5)
```

## Question 2: Pivot Data

```{r}
edu_long <- edu01a %>%
  pivot_longer(
    cols = ends_with("D"), 
    names_to = "surveyID_full", #store original column names (ex. "EST1234D")
    values_to = "enrollment"
  )

#display the first 5 rows
head(edu_long, 5)
```

## Question 3: Extracting the year

```{r}
long_updated <- edu_long %>%
  mutate(
    #extract the 2-digit year from the 8th and 9th characters of surveyID_full 
    surveyID_year = substr(surveyID_full, 8, 9)
    ) %>%
  mutate(
    #convert the 2-digit year into a 4-digit year (assuming all are 1900s)
    year = as.numeric(paste0("19", surveyID_year))
  ) %>%
  mutate(
    #extract the survey ID (first 7 characters of surveyID_full)
    surveyID = substr(surveyID_full, 1, 7)
  ) %>%
  #remove the temporary intermediate column
  select(-surveyID_year)

#display the first 5 rows
head(long_updated, 5)
```

## Question 4: Identifying County Data

```{r}
#identify county rows: ", XX" (where XX is a two-letter state abbreviation)
county_indices <- grep(pattern = ", \\w\\w", long_updated$area_name)

#create county tibble and assign custom classes
county_tibble <- long_updated[county_indices, ]
class(county_tibble) <- c("county", class(county_tibble))

#create non-county tibble and assign custom classes
state_tibble <- long_updated[-county_indices, ]
class(state_tibble) <- c("state", class(state_tibble))

#display the first 10 rows for both data sets
head(county_tibble, 10)
head(state_tibble, 10)
```



























